name = "NadCraft"
author = "Nadwey"
version = "1.0.0-alpha.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0772de3ac5a46ca133739a193ccf12392bf71f56ec238991cc2b2cd7a08ef7cd"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
