name = "NadCraft"
author = "Nadwey"
version = "1.0.0-alpha.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ff46c5290d6bc8913d1a0fd6d7d3ed8555e33c12f2d87e873364511013e22e6"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
