name = "NadCraft"
author = "Nadwey"
version = "1.0.0-alpha.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f22bcbee1a70aeba108dee0f1813866e73dbf0f94d9cb3ff020981b73c289fd1"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
