name = "NadCraft"
author = "Nadwey"
version = "1.0.0-alpha.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7701736a1cdd7a793cf0911d8c5471c868854765cde2529e71d39f34040cdbe5"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
