name = "NadCraft"
author = "Nadwey"
version = "1.0.0-alpha.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c492279866f2d641cbeca9642de035d81653a6d4ea554db3c05ca0c485e9cd7f"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
