name = "NadCraft"
author = "Nadwey"
version = "1.0.0-alpha.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8a83bb98092f4a23c955c9a4a310699aed1921fa359a01495984bbc38c5bf5f"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
