name = "NadCraft"
author = "Nadwey"
version = "1.0.0-alpha.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48d0d58836257cdc379ea8d84e21ddca25e676d63a07bc858b1df820a54d2e1a"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
