name = "NadCraft"
author = "Nadwey"
version = "1.0.0-alpha.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74db36bf0046ee47298f78c4489ab4e5a47c654d17a10fe3a74da7200758e76c"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
