name = "NadCraft"
author = "Nadwey"
version = "1.0.0-alpha.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf727def3fa91e05d692af10af80e2018e5478e1fec3c2a37e6953fee9a353a1"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
